### ISSUE TITLE
Please provide example for how to use Luya-core for standard Yii2 MVC

### ISSUE THREAD

**Issue by ScottHuangZL** [luyadev/luya-kickstarter-core#3]
We may be just need Luya-core to provide "SPA" function in standard Yii2 MVC structure.
Can you help to provide sample**s** for these scenarios?

Btw, 
1.Why Luya use AngularJS instead of Vue?? Or just because of "old history", if yes, any plan to integrate with Vue? thanks.
2.Your Luya-CMS looks good. 

Thanks.

**Comment by nadar** [comment]
How exactly can i help you in this scenario? What do you need? 

1. Take a look at this: https://github.com/luyadev/luya/issues/1824
2. Glad you like it.

**Comment by ScottHuangZL** [comment]
@nadar Look your link already.  Glad to find you also mention Vue as one potential alt. It does spend a long time if you plan change the back end JS stack.

**In your "guide => lesson" => Could you please add examples for just use Luya-core for CRUD?  No related to any CMS, Thanks.**


More and more people use Golang API + Vue/Angular/React to build web. 
Your angle of integrate JS + backend API into one Yii2 framework seems will be more efficiency(from programming point, not from the QPS point)

**Comment by nadar** [comment]
if you need LUYA core only for crud and APIS - you have to install luya module admin only. Thats it :-)

1. composer require luyadev/luya-module-admin
2. add to config
3. run migrate
4. run import
5. run ./vendor/bin/luya admin/setup

There is also a luya headless guide (https://luya.io/guide/concept-headless), and informations about APIs (https://luya.io/guide/ngrest-api) - if you want to connect directly from a frontend javascript client (like making async requests into the apis) there is currently one downside, you need authentication. So you have to provide a bearer auth auth header or access_token to makes calls. This is dangerous as long if you don't set correct permissions for this key. 

So what we need is: We need a module which acts as a proxy between admin module and frontend without authentication which exposes a **public readable auth key**. I think this is what you would looking for right?

So lets build a module ;-) might help?

**Comment by ScottHuangZL** [comment]
I have add luya-module-admin into luya-kickstarter-core project.

Can you provide **a step by step sample** for how to create own control/model/view to show custom web page instead of "hello world"? 

Thanks.

**Comment by nadar** [comment]
https://www.yiiframework.com/doc/guide/2.0/en/structure-controllers
